[package]
name = "nd-arrow-array"
version = "2.0.0"
edition = "2024"

[features]
default = ["arrow-58"]
arrow-56 = ["dep:arrow-56"]
arrow-57 = ["dep:arrow-57"]
arrow-58 = ["dep:arrow-58"]

[dependencies]
arrow-56 = { package = "arrow", version = "56", optional = true }
arrow-57 = { package = "arrow", version = "57", optional = true }
arrow-58 = { package = "arrow", version = "58", optional = true }
thiserror = "2.0"
